### ISSUE TITLE
Uncaught TypeError: render is not a function

### ISSUE THREAD

**Issue by martpie** [sairion/svg-inline-react#1]
Hi,

I'm getting a strange bug. importing the module directly with `import InlineSVG from 'svg-inline-react';` throw the error `render is not a function`, but when I copy paste the content from `node_modules/svg-inline-react/index.js` to a file in my app folder, then import it directly, everything is working.

an idea ?

**Comment by sairion** [comment]
Hello, thanks for report.

I can reproduce that, and It seems a bit weird. It seems something has changed since React 0.14.x or Babel 5.3.x, so they don't encourage using current API...

I think it isn't really worth writing in ES5 anymore. I've just rewritten source with ES2015 and will push 0.2.0 with transpiled and ES2015 source. :)

**Comment by martpie** [comment]
Thanks :+1:
