### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by lynndylanhurley** [sairion/svg-inline-react#15]
Just noticing that there hasn't been any movement with this project for > 5 months. 

@sairion - are you available to review PRs?

Or alternatively, would you be willing to give someone commit access to address issues?

**Comment by sairion** [comment]
Hi, I am available to review PR. As you can see, this project is pretty simple, and since React is supporting SVG almost correctly (it was not when I started svg-inline-loader and this), I don't see good reason to develop this much further. That's the reason this project is under silence, mainly. But I am open to improvements and fixes, if any of them makes sense to me.
