### ISSUE TITLE
Why does it add "xmlns" to all <svg> childrens?

### ISSUE THREAD

**Issue by sandrina-p** [sairion/svg-inline-react#17]
I have this svg:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 17 16" role="img">
   <title>this is a star</title>
   <path d="M16.54 6.221a.375.375 0 0 0-.358-.261h-5.458L9.037.74a.377.377 0 0 0-.716 0L6.634 5.96H1.176a.379.379 0 0 0-.22.684L5.37 9.87l-1.687 5.218a.378.378 0 0 0 .58.423l4.415-3.226 4.416 3.226a.372.372 0 0 0 .442 0 .378.378 0 0 0 .137-.423L11.987 9.87l4.416-3.226a.377.377 0 0 0 .136-.423"></path>
</svg>
```

And when I apply your plugin, it compiles to:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 17 16" role="img">
   <title xmlns="http://www.w3.org/2000/svg">this is a star</title>
   <path xmlns="http://www.w3.org/2000/svg" d="M16.54 6.221a.375.375 0 0 0-.358-.261h-5.458L9.037.74a.377.377 0 0 0-.716 0L6.634 5.96H1.176a.379.379 0 0 0-.22.684L5.37 9.87l-1.687 5.218a.378.378 0 0 0 .58.423l4.415-3.226 4.416 3.226a.372.372 0 0 0 .442 0 .378.378 0 0 0 .137-.423L11.987 9.87l4.416-3.226a.377.377 0 0 0 .136-.423"></path>
</svg>
```

Why the additional xmlns tags on `<title>` and `<path>`?

**Comment by sairion** [comment]
I've never intended to do such thing, so I believe that's bug. But what do you mean by "plugin"? You mean the [loader](https://github.com/sairion/svg-inline-loader)?

**Comment by sandrina-p** [comment]
Ups, sorry, when I use your module like:
```jsx
<SVGInline raw role="img" src={ icon } />;
```

It renders with `xmlns`. Can you fix it please?

**Comment by sairion** [comment]
After a few tests, it is caused by DOMParser's `xmlns` inserting behavior (I'm not entirely sure but I assume it is because I declared parser as `image/svg+xml` - which requires top level element to have proper XML namespace)

After a few thoughts, I will just simply remove DOMParser part and do temporary element trick. This will do the trick (I believe) but could cause another minor behavior changes.
